// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function DownloadTrack(arg1:main.DownloadRequest):Promise<main.DownloadResponse>;

export function GetDefaultDownloadPath():Promise<string>;

export function GetDownloadProgress():Promise<backend.ProgressInfo>;

export function GetVersion():Promise<string>;

export function LoadSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SearchSpotify(arg1:string,arg2:number):Promise<Array<main.SearchResult>>;

export function SelectFolder():Promise<string>;
