// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadTrack(arg1) {
  return window['go']['main']['App']['DownloadTrack'](arg1);
}

export function GetDefaultDownloadPath() {
  return window['go']['main']['App']['GetDefaultDownloadPath']();
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchSpotify(arg1, arg2) {
  return window['go']['main']['App']['SearchSpotify'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
